# Generated by Django 5.0.4 on 2024-05-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_delete_customuser_remove_users_id_users_cgpa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User1',
        ),
    ]
