# Generated by Django 5.0.4 on 2024-05-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_semester1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester2',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calculator.user1')),
                ('subject1', models.CharField(blank=True, max_length=2, null=True)),
                ('subject2', models.CharField(blank=True, max_length=2, null=True)),
                ('subject3', models.CharField(blank=True, max_length=2, null=True)),
                ('subject4', models.CharField(blank=True, max_length=2, null=True)),
                ('subject5', models.CharField(blank=True, max_length=2, null=True)),
                ('subject6', models.CharField(blank=True, max_length=2, null=True)),
                ('subject7', models.CharField(blank=True, max_length=2, null=True)),
                ('subject8', models.CharField(blank=True, max_length=2, null=True)),
                ('subject9', models.CharField(blank=True, max_length=2, null=True)),
                ('gpa', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester3',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calculator.user1')),
                ('subject1', models.CharField(blank=True, max_length=2, null=True)),
                ('subject2', models.CharField(blank=True, max_length=2, null=True)),
                ('subject3', models.CharField(blank=True, max_length=2, null=True)),
                ('subject4', models.CharField(blank=True, max_length=2, null=True)),
                ('subject5', models.CharField(blank=True, max_length=2, null=True)),
                ('subject6', models.CharField(blank=True, max_length=2, null=True)),
                ('subject7', models.CharField(blank=True, max_length=2, null=True)),
                ('subject8', models.CharField(blank=True, max_length=2, null=True)),
                ('subject9', models.CharField(blank=True, max_length=2, null=True)),
                ('gpa', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
